_target_: src.datamodules.covid_datamodule.COVIDDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 32
train_val_test_split: [60, 20, 20]
num_workers: 0
pin_memory: False

csv_name: "train_study_level.csv",
classes: 2
dataset_size: 500
normal: 1
img_size: 128
model: "Densenet121"
scale: 0
shear: 0 
translation: 0
rotation: 0
horizontal_flip: False
vertical_flip: False